server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security-demo
    username: root
    password: root
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver